"""
Jude Hall & Nicolas Child
Zen Payments, Inc.

Script scans the blog sitemap and returns a json 
object of the following format:

[slug, last modified date, image url, image url, image url, ...]
"""

from bs4 import BeautifulSoup
import requests

def scrapeBasicBlogInfo() -> list:
    headers = {
        "User-Agent": "Blog Scraper https://github.com/juderhall/codespaces-get_blog_info)",
        "Email": "nick@zenpayments.com"
    }
    web_address = "https://zenpayments.com/post-sitemap.xml"
    response = requests.get(web_address, headers=headers)
    if response.ok:
        soup = BeautifulSoup(response.text, features="xml").prettify()
        soup = soup.split('<url>')
        unLovedTags = ['</url>', '</urlset>', '</loc>', '</lastmod>', '</image:image>', '</image:loc>', '<!-- XML Sitemap generated by Yoast SEO -->']
        for blog in range(len(soup)):
            for tag in unLovedTags:
                if tag in soup[blog]:
                    soup[blog] = soup[blog].replace(tag, '')
        soup = soup[1:]
        for souper in range(len(soup)):
            soup[souper] = soup[souper].split('<loc>')
            #This is disgusting, I am sorry
            soup[souper] = soup[souper][1:][0].replace('\n', '').replace('<image:loc>', '').replace('<image:image>', '').replace('<lastmod>', '').strip().split(' ')
            while('' in soup[souper]):
                soup[souper].remove('')
        #This is looking like a more delicious soup isnt it?
        for url in range(len(soup)): soup[url][0] = soup[url][0].replace('https://zenpayments.com/', '').replace('/', '')
        return soup